repo:
  public: haskell-server-sdk
  private: haskell-server-sdk-private

circleci:
  linux:
    timeoutMinutes: 45
    image: fpco/stack-build:lts
  context: org-global

documentation:
  title: LaunchDarkly Server-Side SDK for Haskell
  githubPages: true

sdk:
  displayName: "Haskell (server-side)"
